call plug#begin()
	Plug 'preservim/NERDTree'
	Plug 'morhetz/gruvbox'

	" Airline
	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'
	
	Plug 'airblade/vim-gitgutter'

	Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
	Plug 'junegunn/fzf.vim'

call plug#end()


syntax on

" ===== Color ======
set background=dark
colorscheme gruvbox


" =====  Theme ========
" let g:airline#extensions#tabline#formatter = 'default'
let g:airline#extensions#tabline#enabled = 1
" let g:airline#extensions#hunks#enabled=0
" let g:airline#extensions#branch#enabled=1

let g:airline_theme='tmuxline'


" ==== Indentation =====
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab


" ==== Wrap  ====
set wrap       		"Don't wrap lines
set linebreak    	"Wrap lines at convenient points

" ===== number =======\

set rnu
set nu
